### ISSUE TITLE
Export functions

### ISSUE THREAD

**Issue by mathidachuk** [r4fun/hierplane#25]
Need to export:
* `spacyr_default()` (and maybe find a better naming convention for default settings for each hp method ❓ ) 
* `%>%`

**Comment by tyluRp** [comment]
I agree with the rename but not sure what yet. If you want pipes in the package, use this::use_pipe() is all we need!

**Comment by mathidachuk** [comment]
Will be resolved as part of deprecation of hierplane_settings. Track under #43
